
nav:

    - 'HOME': index.md
    - 'PYTHON': python.md
    - 'RUNNER': runner.md
    - 'DEVELOPMENT': development.md
    - 'DONATION': donation.md

site_name: SkyANT

copyright: Copyright &copy; 2020 Iurii Tarasenko
extra:
    generator: true
    homepage: https://skyant.dev
    analytics:
        provider: google
        property: G-TQL7NWWCK3

    social:
        
        - icon: fontawesome/solid/sack-dollar
          link: https://buymeacoffee.com/skyantdev
          name: donation
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/skyantdev
          name: news
        
        - icon: fontawesome/brands/gitlab
          link: https://gitlab.com/skyant
          name: git

        - icon: fontawesome/solid/user-group
          link: https://groups.google.com/a/skyant.dev/g/community
          name: community




###
#  Template
###


docs_dir: site
edit_uri: ""


theme: 
    name: material
    favicon: https://skyant.dev/assets/icons/558614-512-3.png
    logo: https://skyant.dev/assets/icons/558614.svg
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Montserrat
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/gitlab
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - content.code.annotate
        - content.tabs.link


extra_css:
    - /static/css/skyant.css
    - /static/css/hide-title.css
    - /static/css/hide-versions.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: false
                    show_bases: false
                    show_category_heading: false
    - search
    - section-index
    - glightbox
    - include-markdown


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - footnotes
    - attr_list
    - pymdownx.tabbed:
        alternate_style: true 
    - md_in_html
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

