version: 2

mkdocs:
    configuration: mkdocs.yml

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

python:
    install:
        - requirements: .readthedocs.pip

search:
    ranking:
        api/v1/*: -1
        api/v2/*: 4
    ignore:
        - 404.html
    projects:
        - project: skyant-adept
