site_name: SkyANT

docs_dir: site

theme: 
    name: material
    favicon: assets/icons/558614-512-1.png
    logo: assets/icons/558614.svg
    palette:
      primary: amber
      accent: deep purple
    font:
      text: Montserrat Alternates
      code: Roboto Mono

extra:
  generator: false
  homepage: https://skyant.dev
  version:
    provider: mike

extra_css:
  - static/css/skyant.css

copyright: Copyright &copy; 2022 Iurii Tarasenko
