site_name: SkyANT

docs_dir: site

theme: 
    name: material
    favicon: assets/icons/558614-512-3.png
    logo: assets/icons/558614.svg
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Montserrat
        code: Roboto Mono
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - navigation.tabs.sticky


copyright: Copyright &copy; 2020 Iurii Tarasenko
extra:
    generator: true
    homepage: https://skyant.dev

    social:
        
        - icon: fontawesome/solid/sack-dollar
          link: https://buymeacoffee.com/skyantdev
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/skyantdev
        
        - icon: fontawesome/brands/gitlab
          link: https://gitlab.com/skyant

        - icon: fontawesome/solid/user-group
          link: https://groups.google.com/a/skyant.dev/g/community


extra_css:
    - static/css/skyant.css
    - static/css/hide-versions.css
    - static/css/hide-title.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: true
                    show_bases: false
                    show_category_heading: false

    #- search:
    #    indexing: 'full'
    #    projects:
    #        - project: skyantdata
    #        - project: data
    
    - section-index


nav:

    - 'HOME': index.md
    - 'FRAMEWORK': framework.md
    - 'PYTHON': python.md
    - 'RUNNER': runner.md
