site_name: SkyANT

docs_dir: site

theme: 
    name: material
    favicon: assets/icons/558614-512-1.png
    logo: assets/icons/558614.svg
    palette:
      primary: amber
      accent: deep purple
    font:
      text: Montserrat Alternates
      code: Roboto Mono

extra:
  generator: true
  homepage: https://skyant.dev

extra_css:
  - static/css/skyant.css
  - static/css/hide-versions.css
