site_name: SkyANT

docs_dir: site

theme: 
    name: material
    favicon: assets/icons/558614-512-2.png
    logo: assets/icons/558614-4096-2.png
    palette:
      primary: amber
      accent: deep purple
    font:
      text: Montserrat Alternates
      code: Roboto Mono

extra:
  generator: false
  #homepage: https://skyant.dev

copyright: Copyright &copy; 2022 Iurii Tarasenko
